// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcxqmdhhehxkobpwdtck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjeHFtZGhoZWh4a29icHdkdGNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNDg4MTksImV4cCI6MjA2NjcyNDgxOX0.qNrA9Q1FCd5QHpdRSDwxEZVr6EaERvkKKeLqmvpb4AQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});