version: '3.8'

services:
  # Ollama service for local AI models
  ollama:
    image: ollama/ollama:latest
    container_name: video-ai-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    networks:
      - video-ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Python backend service
  video-ai-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-ai-backend
    ports:
      - "8001:8001"
    volumes:
      - backend_data:/app/output
      - backend_temp:/app/temp
      - backend_cache:/app/cache
    environment:
      - OLLAMA_URL=http://ollama:11434
      - PYTHONUNBUFFERED=1
      - TESSDATA_PREFIX=/usr/share/tesseract-ocr/5/tessdata
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - video-ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  ollama_data:
    driver: local
  backend_data:
    driver: local
  backend_temp:
    driver: local
  backend_cache:
    driver: local

networks:
  video-ai-network:
    driver: bridge